apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ala
  name: ala-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ala
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ala
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/IMAGE:TAG
          name: ala
          ports:
            - containerPort: 8080